services:
  l4t-base-cuda:
    image: l4t-base-cuda
    container_name: l4t
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    network_mode: host
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    restart: unless-stopped
